
.job_template: &zig_config
  image: python

stages:          
  - .pre
  - build
  - test

.pre:
  <<: *zig_config
  script:
    - pip install --upgrade pip
    - pip install --user ziglang
    - zig version

build-job:       
  <<: *zig_config
  stage: build
  script:
    - pip install --user ziglang
    - python -m ziglang -- build

unit-test-job:   
  stage: test    
  <<: *zig_config
  script:
    - pip install --user ziglang
    - python -m ziglang -- build test
  timeout: 1 min

example-test-job:
  stage: test
  <<: *zig_config
  needs:
    - build-job
  script:
    - pip install --user ziglang
    - python -m ziglang -- build run -- lambd/test.txt
  timeout: 1 min

bool-test-job:   
  stage: test    
  <<: *zig_config
  needs:
    - build-job
  script:
    - pip install --user ziglang
    - python -m ziglang -- build run -- lambd/bool.txt
  timeout: 1 min
