
.job_template: &zig_config
  image: python

stages:          
  - .pre
  - build
  - test

.pre:
  <<: *zig_config
  script:
    - pip install --upgrade pip
    - pip install --user ziglang
    - zig version

build-job:       
  <<: *zig_config
  stage: build
  script:
    - pip install --user ziglang
    - python -m ziglang build

unit-test:   
  stage: test    
  <<: *zig_config
  script:
    - pip install --user ziglang
    - python -m ziglang build test
  allow_failure: true # TODO. figure out how to include source files
  timeout: 5 min

examples-test:
  stage: test
  <<: *zig_config
  needs:
    - build-job
  script:
    - pip install --user ziglang
    - python -m ziglang build run -- lambd/test.txt
  timeout: 5 min

bool-test:   
  stage: test    
  <<: *zig_config
  needs:
    - build-job
  script:
    - pip install --user ziglang
    - python -m ziglang build run -- lambd/bool.txt
  timeout: 5 min
